s3.bucket=reporting-generated-file

#Replace with your own !!!!!
cloud.aws.region.static=us-east-1
cloud.aws.credentials.accessKey=
cloud.aws.credentials.secretKey=
cloud.aws.stack.auto = false

logging.level.com.antra=DEBUG
logging.file.name=image.service.log

server.port=7777
